### ISSUE TITLE
Add missing team members

### ISSUE THREAD

**Issue by emdupre** [neurodatascience/neurodatascience.github.io#26]
The current team page is still missing several lab members. To fix this, we should:

- [x] Add Irene to team
- [x] Add Gaël to team
- [x] Add Jérôme to team
- [ ] Add Mellie to team
- [x] Add Nikhil to alumni

**Comment by PeerHerholz** [comment]
The respective folks should add themselves via opening a PR from their fork/branch, eh?

**Comment by emdupre** [comment]
makes sense to me ! should we tag them here ?

**Comment by AlexandreHutton** [comment]
Relevant people have been previously added. Closing issue.
