### ISSUE TITLE
Reorganize team members page

### ISSUE THREAD

**Issue by emdupre** [neurodatascience/neurodatascience.github.io#27]
Once all team members are added (#26), there are two remaining concerns:

1. On the current team members page, members are listed in the order in which they created profiles. It would make more sense to have a semi-hierarchical listing, with the PI (@jbpoline ) first. We could put remaining members alphabetically or semi-structured (i.e., visiting researchers, then staff, then postdocs, then grad students, etc) and alphabetically within.

2. The recruiting statement should be updated. At present, it reads:
    > The lab is a diverse group of people interested in connectomics and neuroimaging data science. We are looking to recruit more graduate students and postdocs with backgrounds in engineering, statistics, physics and life sciences.

    We should update this to match the current lab expertise and desired expertise for future lab members.

**Comment by PeerHerholz** [comment]
Re: 

1. I will do the reorganization as soon as the missing folks are added.

2. Should we draft a recruiting statement here or in the slack channel?

**Comment by emdupre** [comment]
Closing this for now. We've updated the member listing with the new website (#43), and kept the recruiting statement as-is.
