### ISSUE TITLE
Finalize lab logo and update favicon to match

### ISSUE THREAD

**Issue by emdupre** [neurodatascience/neurodatascience.github.io#30]
There was a discussion on Slack about using a vectorized version of [this origami brain](https://www.google.com/imgres?imgurl=http%3A%2F%2Frule29.com%2Fwp-content%2Fuploads%2F2012%2F08%2FFold-2-02.jpg&imgrefurl=https%3A%2F%2Frule29.com%2Ffolding-outside-the-box%2F&docid=8tXSBuQrq2NumM&tbnid=6rWk8yK2fgQT9M%3A&vet=10ahUKEwiCorLlif7kAhWEUt8KHUqnBDkQMwisAShdMF0..i&w=500&h=396&safe=active&client=ubuntu&bih=583&biw=1152&q=origami%20brain&ved=0ahUKEwiCorLlif7kAhWEUt8KHUqnBDkQMwisAShdMF0&iact=mrc&uact=8) as the lab logo. We should clarify the licensing on this image. If we are not able to re-distribute it, it would be worth looking at possible logos from [the Noun Project](https://thenounproject.com/). 

Once we decide on a logo, we should add it as a favicon to this website ! In the meantime, we can remove the NetNeuroLab favicon.

**Comment by PeerHerholz** [comment]
There are also a bunch of cool ones [here](https://www.google.com/imgres?imgurl=http%3A%2F%2Frule29.com%2Fwp-content%2Fuploads%2F2012%2F08%2FFold-2-02.jpg&imgrefurl=https%3A%2F%2Frule29.com%2Ffolding-outside-the-box%2F&docid=8tXSBuQrq2NumM&tbnid=6rWk8yK2fgQT9M%3A&vet=10ahUKEwiCorLlif7kAhWEUt8KHUqnBDkQMwisAShdMF0..i&w=500&h=396&safe=active&client=ubuntu&bih=583&biw=1152&q=origami%20brain&ved=0ahUKEwiCorLlif7kAhWEUt8KHUqnBDkQMwisAShdMF0&iact=mrc&uact=8#h=396&imgdii=C9Wuosky1DO5dM&vet=10ahUKEwiCorLlif7kAhWEUt8KHUqnBDkQMwisAShdMF0..i&w=500) that we might get for the fitting license using a free trial.

**Comment by emdupre** [comment]
The updated lab website (#43) shows a logo at some screen sizes, but not all of them. We should make sure that the updated logo / favicon display across media breakpoints.
