### ISSUE TITLE
email addresses for non-students 

### ISSUE THREAD

**Issue by PeerHerholz** [neurodatascience/neurodatascience.github.io#34]
Team members that are not students (BSc, MSc, PhD) should have an `@mcgill.ca` email address. Currently, @jbpoline and @Vincent-wq have an `@mail.mcgill.ca` one listed. This should be changed to avoid problems.

**Comment by Vincent-wq** [comment]
Updated.

**Comment by PeerHerholz** [comment]
@jbpoline's email address is still wrong. Will update that now.
