### ISSUE TITLE
404 page has bad link to home page

### ISSUE THREAD

**Issue by michellewang** [neurodatascience/neurodatascience.github.io#96]
<img width="574" alt="Screenshot 2024-03-26 at 4 49 43 PM" src="https://github.com/neurodatascience/neurodatascience.github.io/assets/29051929/ad9ea296-d4b6-431d-876a-0798357eb6b3">

**Comment by Remi-Gau** [comment]
fixing:

![image](https://github.com/neurodatascience/neurodatascience.github.io/assets/6961185/d87d93e0-25f7-460d-960d-e7903396989b)
